// <auto-generated />
using System;
using LogisticaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728234234_auth")]
    partial class auth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("LogisticaAPI.Entities.Autenticacao.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstituidoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Autenticacao.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Carregamento", b =>
                {
                    b.Property<Guid>("CarregamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeCarregamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeChegada")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeloCaminhao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PesoTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rota")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transportadora")
                        .HasColumnType("TEXT");

                    b.HasKey("CarregamentoId");

                    b.ToTable("Carregamentos");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AlturaUnitario")
                        .HasColumnType("REAL");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Perecivel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PesoUnitario")
                        .HasColumnType("REAL");

                    b.Property<double>("VolumeUnitario")
                        .HasColumnType("REAL");

                    b.HasKey("ItemId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.ItemPalete", b =>
                {
                    b.Property<int>("ItemPaleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemPedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemPaleteId");

                    b.HasIndex("ItemPedidoId");

                    b.HasIndex("PaleteId");

                    b.ToTable("ItensPalete");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.ItemPedido", b =>
                {
                    b.Property<int>("ItemPedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AlturaUnitario")
                        .HasColumnType("REAL");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PesoUnitario")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VolumeUnitario")
                        .HasColumnType("REAL");

                    b.HasKey("ItemPedidoId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PedidoId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Palete", b =>
                {
                    b.Property<int>("PaleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AlturaMaxima")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("CarregamentoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PesoAtual")
                        .HasColumnType("REAL");

                    b.Property<double>("PesoMaximo")
                        .HasColumnType("REAL");

                    b.Property<double>("VolumeAtual")
                        .HasColumnType("REAL");

                    b.Property<double>("VolumeMaximo")
                        .HasColumnType("REAL");

                    b.HasKey("PaleteId");

                    b.HasIndex("CarregamentoId");

                    b.ToTable("Paletes");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoPedido")
                        .HasColumnType("INTEGER");

                    b.HasKey("PedidoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.TipoPalete", b =>
                {
                    b.Property<Guid>("TipoPaleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AlturaMaximo")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PesoMaximo")
                        .HasColumnType("REAL");

                    b.Property<double>("VolumeMaximo")
                        .HasColumnType("REAL");

                    b.HasKey("TipoPaleteId");

                    b.ToTable("TipoPaletes");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Autenticacao.RefreshToken", b =>
                {
                    b.HasOne("LogisticaAPI.Entities.Autenticacao.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.ItemPalete", b =>
                {
                    b.HasOne("LogisticaAPI.Entities.ItemPedido", "ItemPedido")
                        .WithMany("Alocacoes")
                        .HasForeignKey("ItemPedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaAPI.Entities.Palete", "Palete")
                        .WithMany("Itens")
                        .HasForeignKey("PaleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemPedido");

                    b.Navigation("Palete");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.ItemPedido", b =>
                {
                    b.HasOne("LogisticaAPI.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaAPI.Entities.Pedido", "Pedido")
                        .WithMany("ItensPedido")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Palete", b =>
                {
                    b.HasOne("LogisticaAPI.Entities.Carregamento", "Carregamento")
                        .WithMany("Paletes")
                        .HasForeignKey("CarregamentoId");

                    b.Navigation("Carregamento");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Autenticacao.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Carregamento", b =>
                {
                    b.Navigation("Paletes");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.ItemPedido", b =>
                {
                    b.Navigation("Alocacoes");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Palete", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Pedido", b =>
                {
                    b.Navigation("ItensPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
