// <auto-generated />
using System;
using LogisticaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718011241_TipoPaleteRepository")]
    partial class TipoPaleteRepository
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("LogisticaAPI.Entities.Carregamento", b =>
                {
                    b.Property<Guid>("CarregamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeCarregamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeChegada")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeloCaminhao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PesoTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rota")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transportadora")
                        .HasColumnType("TEXT");

                    b.HasKey("CarregamentoId");

                    b.ToTable("Carregamentos");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.ItemPalete", b =>
                {
                    b.Property<Guid>("ItemPaleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AlturaUnitario")
                        .HasColumnType("REAL");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaleteId")
                        .HasColumnType("TEXT");

                    b.Property<double>("PesoUnitario")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VolumeUnitario")
                        .HasColumnType("REAL");

                    b.HasKey("ItemPaleteId");

                    b.HasIndex("PaleteId");

                    b.ToTable("ItemPalete");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Palete", b =>
                {
                    b.Property<Guid>("PaleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AlturaMaxima")
                        .HasColumnType("REAL");

                    b.Property<Guid>("CarregamentoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PesoAtual")
                        .HasColumnType("REAL");

                    b.Property<double>("PesoMaximo")
                        .HasColumnType("REAL");

                    b.Property<double>("VolumeAtual")
                        .HasColumnType("REAL");

                    b.Property<double>("VolumeMaximo")
                        .HasColumnType("REAL");

                    b.HasKey("PaleteId");

                    b.HasIndex("CarregamentoId");

                    b.ToTable("Palete");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.TipoPalete", b =>
                {
                    b.Property<Guid>("TipoPaleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AlturaMaximo")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PesoMaximo")
                        .HasColumnType("REAL");

                    b.Property<double>("VolumeMaximo")
                        .HasColumnType("REAL");

                    b.HasKey("TipoPaleteId");

                    b.ToTable("TipoPaletes");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.ItemPalete", b =>
                {
                    b.HasOne("LogisticaAPI.Entities.Palete", "Palete")
                        .WithMany("Itens")
                        .HasForeignKey("PaleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Palete");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Palete", b =>
                {
                    b.HasOne("LogisticaAPI.Entities.Carregamento", "Carregamento")
                        .WithMany("Paletes")
                        .HasForeignKey("CarregamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carregamento");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Carregamento", b =>
                {
                    b.Navigation("Paletes");
                });

            modelBuilder.Entity("LogisticaAPI.Entities.Palete", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
