// <auto-generated />
using System;
using LogisticaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717013756_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("LogisticaAPI.Entities.Carregamento", b =>
                {
                    b.Property<Guid>("CarregamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeCarregamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeChegada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rota")
                        .HasColumnType("TEXT");

                    b.HasKey("CarregamentoId");

                    b.ToTable("Carregamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
